name: Sync Language Repos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-language-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SYNC_L10N_APP_ID }}
          private-key: ${{ secrets.SYNC_L10N_APP_PRIVATE_KEY }}
          owner: MahoCommerce

      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Sync language folders and tag
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          for dir in *_*/; do
            lang=${dir%/}
            echo "Processing $lang"
          
            # Clone the language-specific repo
            git clone https://x-access-token:$GH_TOKEN@github.com/mahocommerce/maho-language-$lang.git temp_$lang
          
            # Copy contents from main repo to language-specific repo
            rsync -av --delete $lang/ temp_$lang/
          
            # Check for changes
            cd temp_$lang
            if [[ $(git status --porcelain) ]]; then
              echo "Changes detected in $lang"
              git add .
              git commit -m "Sync changes from main repository - ${{ steps.date.outputs.DATE }}"
              git push origin main
          
              # Tag new version
              git tag -a ${{ steps.date.outputs.DATE }} -m "Version ${{ steps.date.outputs.DATE }}"
              git push origin --tags
          
              echo "Tagged new version ${{ steps.date.outputs.DATE }} for $lang"
            else
              echo "No changes in $lang"
            fi
            cd ..
          
            # Clean up
            rm -rf temp_$lang
          done